### ISSUE TITLE
Feature Request : Get start time of event when do the dragging on scheduler.

### ISSUE THREAD

**Issue by desilvaNSP** [StephenChou1017/react-big-scheduler#104]
Hi @StephenChou1017,

Can you give me idea about how to get the start time on event when dragging on scheduler. When do the dragging x, y position is changing according to that on the event. I need to get start time on that point.

Thanks
Sandun

**Comment by StephenChou1017** [comment]
You mean to get the preview start time of event in real time during the dragging process?

**Comment by desilvaNSP** [comment]
Hi @Stephen, Yes definately, Is there posible way to do it?

**Comment by StephenChou1017** [comment]
Yes it's possible, I need to add a callback function in Scheduler. I'll do it.

**Comment by desilvaNSP** [comment]
Brilliant, Thanks for your contribution on this.

**Comment by desilvaNSP** [comment]
@StephenChou1017, Hope you are doing well. Did you able to look on my feature request. I am looking forward your feedback on that. Appreciate very much on your contribution.

**Comment by StephenChou1017** [comment]
@desilvaNSP 
Hi, I've added a movingEvent func in Scheduler and you can try it now. And I subscribe this func in the [DragAndDrop](https://github.com/StephenChou1017/react-big-scheduler/blob/master/example/DragAndDrop.js) demo.

**Comment by desilvaNSP** [comment]
@StephenChou1017, Appreciate very much on this.

**Comment by desilvaNSP** [comment]
@StephenChou1017, It was worked. Thanks for help me on this feature.
