### ISSUE TITLE
Vertical Resource View as FullCalender

### ISSUE THREAD

**Issue by desilvaNSP** [StephenChou1017/react-big-scheduler#108]
Hi @StephenChou1017, 

Good day,

Do you have idea for implement **vertical resource view** as fullCalender in your liabary. Is there easy way to enable that particular feature in your liabary. Feature was, User should able to create events by merging vertical resources to one. For current implementation, we can only do the event creation for inside the one resource.

[vertical-resource-view-in-fullcalender.io](https://fullcalendar.io/releases/fullcalendar-scheduler/1.9.4/demos/vertical-resource-view.html)

<img width="909" alt="Screen Shot 2019-03-17 at 1 07 33 AM" src="https://user-images.githubusercontent.com/3749657/54480668-33caf280-4851-11e9-9a96-4566ee9149c9.png">

Appriciate your support.

Thanks

**Comment by bubamacko** [comment]
this was solved?
