### ISSUE TITLE
Feature Request : Monthly Calendar View

### ISSUE THREAD

**Issue by desilvaNSP** [StephenChou1017/react-big-scheduler#109]
Hi @StephenChou1017,

Is there posible way to enable monthly calender view following way. Each events inside the month should be able to show according to the following manager. Do you have idea for enable those functionalities to the your Lib. I like to give contribute for that. How we start that. I am looking forward your comments.

![image](https://user-images.githubusercontent.com/3749657/54480891-4c88d780-4854-11e9-9463-967790c4fc8a.png)

Thanks

**Comment by briantical** [comment]
@desilvaNSP did you find a solution to this?
