### ISSUE TITLE
Disable +Nmore popover

### ISSUE THREAD

**Issue by IGI-111** [StephenChou1017/react-big-scheduler#11]
I have a schedule with a whole bunch of events in a single ressource and I want to display all the events with no height limit.

Essentially I want to disable the +Nmore popover and always display the events instead, and I can't figure out how to do it.

Is there any way I can achieve that? And if not I guess this is a feature request.

**Comment by StephenChou1017** [comment]
SchedulerData.config has some *MaxEvents(dayMaxEvents, weekMaxEvents etc) properties with default value 99, you can set them to 9999(or bigger) when you need, to disable +Nmore popover.

**Comment by IGI-111** [comment]
Yeah sorry, should have mentionned that I did try setting those options to high values, say 10000, and I still got some +Nmore. And some weird behavior.

The N values have seemingly no relation to the actual number of events, and some even get placed when i have a small number of them.

![](https://i.imgur.com/Bs5jgPd.png)
![](https://i.imgur.com/HzY2qeZ.png)
![](https://i.imgur.com/8I5ShvP.png)

I suppose that's related to the bug mentionned in the changelog, but nevertheless I think it'd be nice to have an option to disable the popovers alltogether. Like setting max event values to 0 or something.

**Comment by StephenChou1017** [comment]
Sorry, it probably is a bug of scheduler, can you send your code(include the resources and events data) to me and let me have a look, my email address is 27788280@qq.com.

**Comment by StephenChou1017** [comment]
An easy way is that you fork my latest repo, in the [basic example](https://github.com/StephenChou1017/react-big-scheduler/blob/master/example/Basic.js), set your resources and events json data to SchedulerData object, and then share the code with me:

`schedulerData.setResources(your.resources);`
`schedulerData.setEvents(your.events);`

**Comment by StephenChou1017** [comment]
@IGI-111 
Hi, does the issue still exist?

**Comment by IGI-111** [comment]
I don't have the code at hand right now but I'll send an example later today.

**Comment by IGI-111** [comment]
My machine is having some trouble at the moment so I can't reproduce a minimal example as of now, but for the record [here is my data.](https://gist.github.com/IGI-111/9adfc8cbe46e1e3c31ced1ce18b09d00)

**Comment by meecrobe** [comment]
+1
Th same problem in Day view.

```dayMaxEvents``` property is set to ```99``` but only one event is being rendered.

![image](https://user-images.githubusercontent.com/8003440/42928828-08d61136-8b41-11e8-8478-0cc07c34f21b.png)

**Comment by StephenChou1017** [comment]
@meecrobe 
You can send your resources and events json to me too. I'll have a look.

**Comment by StephenChou1017** [comment]
@IGI-111 
I've tested with your events data, and find that the event array isn't sorted in ascending order by event.start property, and this causes the +Nmore rendering errors in the Scheduler component. **The event array set to the SchedulerData should be sorted in ascending order by event.start property.**

@meecrobe 
You may also check your event array, to see whether there is the same problem:-)

**Comment by IGI-111** [comment]
Thanks. This most definitely fixes it so I'm going to close.

Hell it's even said right there in the documentation so I should probably have seen it, I may simply suggest making the requirement more evident.
