### ISSUE TITLE
Swap events between two scheduler 

### ISSUE THREAD

**Issue by KirillTerentiev** [StephenChou1017/react-big-scheduler#114]
For the reasons of absence of nested resources in scheduler, i've got an idea to render two separate schedulers. Can i drag and drop from one scheduler to another ones events i needed?

**Comment by StephenChou1017** [comment]
@KirillTerentiev 
Yes, it's possible, see [this issue](https://github.com/StephenChou1017/react-big-scheduler/issues/41)
