### ISSUE TITLE
Feature Request: Toggle Headers On and Off

### ISSUE THREAD

**Issue by heynellywelly** [StephenChou1017/react-big-scheduler#12]
Hi there!

I was wondering if you could create props for the headers so we could choose to toggle it on / off? Thank you!

**Comment by StephenChou1017** [comment]
@heynellywelly 
Hi, I added a new property SchedulerData.config.headerEnabled to achieve this:-)

**Comment by heynellywelly** [comment]
Hi Stephen, thank you so much! :D Awesome work with the React Scheduler btw!
