### ISSUE TITLE
Events height should be flexible

### ISSUE THREAD

**Issue by zainbconf** [StephenChou1017/react-big-scheduler#137]
Hello,

I want to use custom event style, I found this method 'eventItemTemplateResolver' to design custom event style. But if we increase height of the event, it overlaps the other event, if there is some event with same resource and time.
![Capture](https://user-images.githubusercontent.com/47576151/58338354-963b0300-7e3f-11e9-8b49-91d30011dafe.PNG)

**Comment by StephenChou1017** [comment]
Hi, you need to set schedulerData.config.eventItemHeight and eventItemLineHeight to the correct value.

**Comment by zainbconf** [comment]
@StephenChou1017 Thanks man, it works!
