### ISSUE TITLE
[BUG] Order of events cause them not to be rendered in certain cases

### ISSUE THREAD

**Issue by ThomasCarca** [StephenChou1017/react-big-scheduler#138]
Hello ! Thank you very much for this great project, I find it very useful !

I'm running into a bug when overlapping events in a certain order.

Imagine having two events 
```
const e1 = {
  id: 1,
  start: "2017-12-18 09:30:00",
  end: "2017-12-18 12:30:00",
  resourceId: "r1",
  title: "A"
};

const e2 = {
  id: 2,
  start: "2017-12-18 11:00:00",
  end: "2017-12-18 14:30:00",
  resourceId: "r1",
  title: "B"
};
```

for the following resource : 
```
const r1 = [
  {
    id: "r1",
    name: "Resource1"
  }
];
```

Passing the events in the following order works as espected : `[e1, e2]`
![react-big-scheduler-bug-1](https://user-images.githubusercontent.com/24562239/58490935-542afd80-816e-11e9-8210-7bf6b483d16e.png)

But if you pass the events in this order : `[e2, e1]`
![react-big-scheduler-bug-2](https://user-images.githubusercontent.com/24562239/58490971-660ca080-816e-11e9-86cb-1c28492d9d44.png)

... you can see event B is not rendered. It reappears once you move event e1, though.

I have no idea what could cause this behavior. 

A workaround I've found for now that is not ideal is to sort the events by starting date. This seems to resolve the issue.

**[Here is a Code Sandbox that showcases the issue](https://codesandbox.io/s/quirky-kirch-ccowj?fontsize=14)**

**Comment by StephenChou1017** [comment]
@ThomasCarca 
Hi, it's designed like that. The event array set to the SchedulerData should be sorted in ascending order by event.start property, otherwise there will be many rendering errors in the Scheduler component.

**Comment by ThomasCarca** [comment]
Hi, thanks for the quick answer. Cool to know it's not a bug. Is it specified somewhere in the docs?

**Comment by StephenChou1017** [comment]
Yes, in the README.md

**Comment by ThomasCarca** [comment]
Ah yes, indeed. Thanks !
