### ISSUE TITLE
when I am using slotItemTemplateResolver function Toggle is not working 

### ISSUE THREAD

**Issue by mounikaalla-rahi** [StephenChou1017/react-big-scheduler#139]
I am using custom slotItemTemplateResolver = (schedulerData, slot, slotClickedFunc, width, clsName) to customize the Resources Cell. When I using the slotItemTemplateResolver function toggle is not working. Can you please help me in getting the toggle button  appended to my custom resource styling.

![Screen Shot 2019-05-28 at 2 43 50 PM](https://user-images.githubusercontent.com/46454633/58514520-0e166f80-8157-11e9-81ad-590f365d752b.png)

Thanks
![Screen Shot 2019-05-28 at 2 46 41 PM](https://user-images.githubusercontent.com/46454633/58514671-7402f700-8157-11e9-91b1-feb61e3b83bd.png)

**Comment by StephenChou1017** [comment]
@mounikaalla-rahi 
Hi, you may refer to the [ResourceView.js](https://github.com/StephenChou1017/react-big-scheduler/blob/master/src/ResourceView.js) to customize your slotItemTemplateResolver func.

**Comment by mounikaalla-rahi** [comment]
@StephenChou1017  Thanks Stephen.It is working now. I got the clue what is missing from the ResourceView.js

Thanks again
