### ISSUE TITLE
TypeError: Cannot read property '_setDocumentWidth' of undefined

### ISSUE THREAD

**Issue by phoon0901** [StephenChou1017/react-big-scheduler#148]
I tried to follow your [demo ](https://github.com/StephenChou1017/react-big-scheduler-demo). However, I received an error TypeError: Cannot read property '_setDocumentWidth' of undefined at index.js in line 173. `schedulerData._setDocumentWidth(document.documentElement.clientWidth);`

Anyone know how to solve this?

**Comment by vladdedita** [comment]
Did you manage to solve this? I'm running into the same problem.

**Comment by dandanknight** [comment]
I think this will be due to the scheduleData object not been created in time before the component renders

**Comment by dgo2dance** [comment]
Anyone know how to solve this?

**Comment by SirPhemmiey** [comment]
Guys, any luck with this please? @duanshuyong0 @dandanknight @phoon0901

**Comment by despatates** [comment]
I encountered this issue, this was because `schedulerData` was not correctly initialized in my class.

```js
class MyPlanning extends React.Component {
  schedulerData = undefined;

  componentDidMount() {
    this.schedulerData = new SchedulerData(/* ... */);
    // [ ... ]
  }

  render() {
    return (
      <Scheduler
        schedulerData={this.schedulerData} // <- this.schedulerData is undefined.
        prevClick={this.prevClick}
        nextClick={this.nextClick}
        onSelectDate={this.onSelectDate}
        onViewChange={this.onViewChange}
        eventItemClick={this.eventClicked}
      />
    );
  }
}
```

`this.schedulerData` is `undefined` at first render because `componentDidMount()` is called after first `render()` call.
So check `schedulerData` before using it.

```js
render() {
  return this.schedulerData ? <Scheduler schedulerData={this.schedulerData} { ... } /> : null;
}
```

Hope this helps.
