### ISSUE TITLE
Change events height?

### ISSUE THREAD

**Issue by awesomearpit** [StephenChou1017/react-big-scheduler#152]
Is it possible to change events height?
Because when I changed the height of events then two events overlap to each other.
So please give me solution ASAP.
Thanks

**Comment by IhorHolovatsky** [comment]
Hi!
I had same question,

You just need override config values of eventItemHeight and eventItemLineHeight

Check config https://github.com/StephenChou1017/react-big-scheduler/blob/master/src/config.js#L34
how to override config: https://github.com/StephenChou1017/react-big-scheduler#constructor

my example:
`  const schedulerModel = new SchedulerData(new moment().format(DATE_FORMAT), ViewTypes.Week, false, false,
            {
                nonAgendaOtherCellHeaderFormat: 'dddd, MMMM D',
                eventItemHeight: 50,
                eventItemLineHeight: 54
            },
            {
                isNonWorkingTimeFunc: () => false
            }
        );`

**Comment by awesomearpit** [comment]
@IhorHolovatsky Its working. Thanks
