### ISSUE TITLE
[npm] Could you release a beta version of the next set of features into npm

### ISSUE THREAD

**Issue by Jokinen** [StephenChou1017/react-big-scheduler#16]
Hi,

the version in [npm](https://www.npmjs.com/package/react-big-scheduler) is about four months old. You have since added some new features and made improvements in this repository, but we, the library users, can't yet take advantage of those.

I can appreciate that releasing a npm version might be a a burden, maybe due to documentation concerns for instance. But could you consider releasing the changes with a beta tag for instance? In that case you wouldn't need to complete the release, those of us who would want to use the improvements would get to do so and maybe you'd even get some beta testing out of us.

Thanks for the library and effort.

**Comment by StephenChou1017** [comment]
@Jokinen
Hi, l'm working on it, and there still are a few script errors in IE now, I'll publish one after fixing them, thank you:)
