### ISSUE TITLE
Minute step is not set properly

### ISSUE THREAD

**Issue by wcschoonover** [StephenChou1017/react-big-scheduler#17]
Implementing the basic example in my application results in the following error: "Error: Minute step is not set properly - 60 minutes must be divisible without remainder by this number". This is occurring in 0.2.1

This occurs at this line:
`let schedulerData = new SchedulerData('2017-12-18', ViewTypes.Week);`
And will also occur when using moment and DATE_FORMAT:
`let schedulerData = new SchedulerData(new moment("2017-12-18").format(DATE_FORMAT), ViewTypes.Week);`

```
SchedulerData.js:702 Uncaught Error: Minute step is not set properly - 60 minutes must be divisible without remainder by this number
    at SchedulerData._validateMinuteStep (SchedulerData.js:702)
    at new SchedulerData (SchedulerData.js:60)
```

**Comment by StephenChou1017** [comment]
The SchedulerData.config.minuteStep is minute step for day view type in non-agenda view, can be 10, 12, 15, 20, 30, 60, etc, default 30. Did you modify it?

**Comment by wcschoonover** [comment]
I did not modify it, I pulled in the basic example to try standing it up, and that was the error I received. The only modifications I made were removing the Nav (line 29), Tips (line 48), alert confirms (lines 98, 122, 131, 140), and the Basic Example header (line 31). Everything else matches this example: https://github.com/StephenChou1017/react-big-scheduler/blob/master/example/Basic.js

**Comment by StephenChou1017** [comment]
Ok, I'll have a look.

**Comment by wcschoonover** [comment]
This appears to be an issue with my build of React 16.4.1. Thanks for your help @StephenChou1017
