### ISSUE TITLE
how to change the color of the table like this?

### ISSUE THREAD

**Issue by RianKhanafi** [StephenChou1017/react-big-scheduler#197]
![color](https://user-images.githubusercontent.com/51011550/82292470-2c632400-99d5-11ea-8c05-0dcf5729ff5b.png)

**Comment by RianKhanafi** [comment]
yes. I have found it

**Comment by usahai** [comment]
Hey, do you have any idea how I can change the color of the header row? -- i.e. first, last, header

**Comment by RianKhanafi** [comment]
yes, clone peckage,
you can search for ResourceEvents.js file
at line 454 in the connectDropTarget

and you add styles you want, like:
 backgroundColor:
                  index % 2 == 0 ? "rgba(0,0,0,0.04)" : "rgba(0,0,0,0.02)",
or whatever
