### ISSUE TITLE
Basic setup (and also Basic example) not working

### ISSUE THREAD

**Issue by alesdvorakcz** [StephenChou1017/react-big-scheduler#2]
I followed instructions from "Use and Setup" and it gave me error: 
```
Uncaught TypeError: Cannot read property 'string' of undefined
    at Object../node_modules/antd/lib/grid/row.js (row.js:108)
```

The same error is shown when I copy paste Basic example. I tested it on newly created create-react-app.
Here is the repo: https://github.com/alesdvorakcz/react-big-scheduler-test

**Comment by StephenChou1017** [comment]
@alesdvorakcz
hi, I have seen your code in the repo, I noticed that you used the react v16, which is not supported yet. The current react and nodejs version I use are v15.4.2 and v6.9.2, higher version support is in my schedule.
Another problem is the react-big-scheduler

**Comment by StephenChou1017** [comment]
Another problem is the react-big-scheduler use react-dnd to achieve drag and drop, so the Scheduler component should be placed in a DragDropContext(father or ancestor).
Maybe the "Use and Setup" isn't clear enough, my fault, you can clone my repo and try to refactor to react 16 yourself first:)

**Comment by alesdvorakcz** [comment]
OK, thanks for the info, I will try it and let you know

**Comment by 5angel** [comment]
Any update on this? Decided to try this lib, but stuck with the same error.

**Comment by StephenChou1017** [comment]
@5angel  @alesdvorakcz  I published one version in npm today, which supports react 16, you can try it again :-)

**Comment by alesdvorakcz** [comment]
I know my colleague sent that PR :) thanks. I think we can close this

**Comment by StephenChou1017** [comment]
ok, henryroach is your colleague, how small world:-)
