### ISSUE TITLE
Show week number?

### ISSUE THREAD

**Issue by nimesha95** [StephenChou1017/react-big-scheduler#23]
Hi, is is possible to show week number in the "Quater" view?
Thanks

**Comment by StephenChou1017** [comment]
Show in where?

**Comment by nimesha95** [comment]
Display along with the header (day)? (maybe show only in the Monday on each week)

**Comment by StephenChou1017** [comment]
If this, you can use Scheduler.nonAgendaCellHeaderTemplateResolver to achieve it, see [this example(https://stephenchou1017.github.io/scheduler/#/customtableheaders)]

**Comment by nimesha95** [comment]
Thanks.. couldn't find it before. Keep up the good work
