### ISSUE TITLE
Is it possible to handle click on the date header in week view?

### ISSUE THREAD

**Issue by storminteractive** [StephenChou1017/react-big-scheduler#233]
I can't find in documentation if there is any handler for clicking on a specific day in week view. It would be very user friendly to have a functionality supporting clicking on a date in week view, let's say where it says "Wed 12/20" and then handle this event to change the view into a day view for 12/20. Is it possible? If not can you suggest any workaround?

Thanks!

**Comment by chaunt1** [comment]
use the `nonAgendaCellHeaderTemplateResolver` function. you can customize the header

**Comment by storminteractive** [comment]
Thank you
