### ISSUE TITLE
Feature Request: Show More information in resource name cell

### ISSUE THREAD

**Issue by nimesha95** [StephenChou1017/react-big-scheduler#24]
Like the title says, is there a way to do that currently? 

Example: Show a name of a person and his designation under his name in the resource name column

Thanks, keep up the good work

**Comment by StephenChou1017** [comment]
@nimesha95 
You can use Scheduler.slotItemTemplateResolver to achieve this

**Comment by nimesha95** [comment]
@StephenChou1017  hi, sorry bother again, is there  a way to use custom viewTypes? 
As an example, let's say i want to show 6 weeks instead of 4 weeks in month view?

I see that you are handling this logic in "SchedularData,js".
Is there a easy way to do this without modifying that logic?
Thanks

**Comment by StephenChou1017** [comment]
Why do you want to show 6 weeks instead of 4 weeks in month view,  month view is month view, starts from 1 and stop to 30(or 31)?

**Comment by StephenChou1017** [comment]
slotItemTemplateResolver(schedulerData, slot, slotClickedFunc, width, clsName)， you can use it like eventItemTemplateResolver, see [this example](https://github.com/StephenChou1017/react-big-scheduler/blob/master/example/CustomEventStyle.js)

**Comment by StephenChou1017** [comment]
Then I suggest you use the quarter view, if you really want to achieve this, you need to modify the code in SchedulerData.js, compute the startDate and endDate first, then compute the headers array, and then compute the renderData.

**Comment by nimesha95** [comment]
Yes, i guess i will go with the second option. Thanks for the reply
