### ISSUE TITLE
give a percentage to schedulerWidth

### ISSUE THREAD

**Issue by nellyhws** [StephenChou1017/react-big-scheduler#36]
Hello Stephen,
  Could you tell me is it possible that I can set the schedulerWidth with percentage instead of giving a fixed width?
  I know I can give schedulerWidth a fixed width like this:
  ` schedulerData.config.schedulerWidth = '600';`
  But what I want is:
  ` schedulerData.config.schedulerWidth = '100%';`
  So that I can make sure that the scheduler never out of range.

Thank you so much.

**Comment by nimesha95** [comment]
Hi, 
I faced the same issue and resolved using this, 

`var screen_width = window.screen.width;`

This captures the whole width of the browser window
[more info](https://www.w3schools.com/js/js_window_screen.asp)

**Comment by nellyhws** [comment]
> Hi,
> I faced the same issue and resolved using this,
> 
> `var screen_width = window.screen.width;`
> 
> This captures the whole width of the browser window
> [more info](https://www.w3schools.com/js/js_window_screen.asp)

Hi,
  Thank you for your response. However, this method cannot resolve my problem, because what I need capture is not the browser window but the <div> contains the scheduler. :(

**Comment by nimesha95** [comment]
funny thing, i also faced same thing again, what i did was this, 
```
<div ref={leaflet => { this.leaflet = leaflet }}>
//here the div (container) that you need to get the size 
</div>
```

and then in componentDidMount life cycle method i would call following and set the width of the bigScheduler there. 
`var width = this.leaflet.offsetWidth`

Hope this helps 😄

**Comment by StephenChou1017** [comment]
Not supported yet, you need to resolve the width of the div which contains the Scheduler component ，and then set it to schedulerData.config.schedulerWidth, meanwhile you'd better reset the schedulerData.config.weekCellWidth, there will be blank area if schedulerData.config.weekCellWidth * 7 < schedulerData.config.schedulerWidth.

**Comment by nellyhws** [comment]
> funny thing, i also faced same thing again, what i did was this,
> covered the container holding bigscheduler by a div like this.
> 
> ```
> <div ref={leaflet => { this.leaflet = leaflet }}>
> //here the div (container) that you need to get the size 
> </div>
> ```
> and then in componentDidMount life cycle method i would call following and set the width of the bigScheduler there.
> `var width = this.leaflet.offsetWidth`
> 
> Hope this helps



> Not supported yet, you need to resolve the width of the div which contains the Scheduler component ，and then set it to schedulerData.config.schedulerWidth, meanwhile you'd better reset the schedulerData.config.weekCellWidth(if you have week view), there will be blank area if schedulerData.config.weekCellWidth * 7 + schedulerData.config.weekResourceTableWidth < schedulerData.config.schedulerWidth.

Hi, 
I resolved my problem.
I use the 'react-measure' plugin


Thank you :)
