### ISSUE TITLE
Change minutes interval in day view

### ISSUE THREAD

**Issue by henryroach** [StephenChou1017/react-big-scheduler#4]
Hello, is it possible to change minutes interval in day view from 30 minutes to 15? If it's not currently possible, do you plan this feature in future?

Thank you

**Comment by StephenChou1017** [comment]
Yes, it's possible, but not currently:-), I'll add it into the to-do list.


------------------ 原始邮件 ------------------
发件人: "henryroach"<notifications@github.com>;
发送时间: 2018年4月19日(星期四) 下午3:21
收件人: "StephenChou1017/react-big-scheduler"<react-big-scheduler@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: [StephenChou1017/react-big-scheduler] Change minutes interval in dayview (#4)




Hello, is it possible to change minutes interval in day view from 30 minutes to 15? If it's not currently possible, do you plan this feature in future?
 
Thank you

**Comment by henryroach** [comment]
Ok, I have basic functionality working, Could you please take a look on the latest version on my github and write me some comments (if you want a different way to implement it)? There is new configuration property minuteStep, which indicates one "span" time in minutes. So far I've tested just 15 and 10 minutes and it seems to be working.

**Comment by StephenChou1017** [comment]
@henryroach 
I've downloaded your code and had a try.  I agree with you on adding a new property "minuteStep" to the SchedulerData.config object,  but I think we can merge three head cells (two if set to 15) into one(one head cell per hour), just like the [fullcalendar-scheduler ](https://fullcalendar.io/releases/fullcalendar-scheduler/1.9.4/demos/scale.html)does, what do you think:-)

**Comment by henryroach** [comment]
Ok, sounds good, i will adjust the solution and let you know ;-)
