### ISSUE TITLE
dayMaxEvents not working for values > 2

### ISSUE THREAD

**Issue by perannum** [StephenChou1017/react-big-scheduler#43]
If i set the configuration for less than 2 value the '+N more' works fines, but no value greater than 2 is working. It shows max of 2 events and then '+N more' appears.

**Comment by StephenChou1017** [comment]
@perannum
is the event array sorted in ascending order by event.start property, otherwise there will be some rendering errors?

**Comment by perannum** [comment]
That was the case! The events array was not sorted. After sorting the array in ascending order the problem is fixed. Thanks!
