### ISSUE TITLE
Error after `npm run build`

### ISSUE THREAD

**Issue by zeyadetman** [StephenChou1017/react-big-scheduler#45]
I got this error 

> Error: Minified React error #254; visit https://reactjs.org/docs/error-decoder.html?invariant=254&args[]=startResizer for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

After i run `npm run build` and the scheduler page doesn't work anymore, although it works correctly on `npm start`.

**Comment by StephenChou1017** [comment]
@zeyadetman 
Hi, the `npm run build` command is used to publish npm version, and [this repo](https://github.com/StephenChou1017/react-big-scheduler-demo) is a demo that use npm version. If your scheduler page is running locally, you can use the `npm run example` command.

**Comment by zeyadetman** [comment]
It's a problem in devOps thanks @StephenChou1017 .
