### ISSUE TITLE
Publish on NPM

### ISSUE THREAD

**Issue by NguyenJeremy69** [StephenChou1017/react-big-scheduler#46]
Hi,
I wanted to know when 'react-big-scheduler' with the 'Custom time window' will be publish on npm?

Thank you in advance for your help!

**Comment by StephenChou1017** [comment]
@NguyenJeremy69 
Hi, I'll publish one asap:-)

**Comment by StephenChou1017** [comment]
@NguyenJeremy69 I've published a new version 0.2.2 in npm.

**Comment by NguyenJeremy69** [comment]
Thank you! :)
