### ISSUE TITLE
slotItemTemplateResolver should return the item from the resources

### ISSUE THREAD

**Issue by angel-git** [StephenChou1017/react-big-scheduler#47]
Hello,
If I want to have a custom template on the resources table (left side of calendar) the method called by `slotItemTemplateResolver` is giving me and item with the following:
```javascript
{
                slotId: ...,
                slotName: ....,
                rowHeight: ....,
                headerItems: ....
}
```

Even though I'm passing on `schedulerData.setResources` a complete object like:
```javascript
{
                id: data.id,
                name: data.title,
                complexObject: {....}
}
```

When my custom template method is called I only get `slotId`, `slotName` etc... but i would like to have my object back the same as I set it on the `schedulerData.setResources`

The workaround for now is `slotItemTemplateResolver` is sending me back the `id` of my item and then i can search for it on my properties but I think the scheduler should return it as well.

Or maybe i have something wrong :)

Thank you so much!

**Comment by StephenChou1017** [comment]
@angel-git 
Hi, you can use `schedulerData.getSlotById(slotId)` to get your complete object after you get the slotId:-)

**Comment by angel-git** [comment]
that also works! thanks! ;)
