### ISSUE TITLE
Change the background color of cells dynamically.

### ISSUE THREAD

**Issue by nimesha95** [StephenChou1017/react-big-scheduler#53]
Hi.. Is this possible to do? 
What i want to do is change the background color of a cell dynamically (if some condition becomes true, then change color). 
Is there a function like `getSummary` to change the className or background color of the body cell?
Thanks

**Comment by StephenChou1017** [comment]
I'll try:-)

**Comment by nimesha95** [comment]
@StephenChou1017 hi.. 
A feature suggestion. It would be better if there is a function like `scrollToCell(cell_id)` rather than `scrollToToday` 
Keep up the good work

**Comment by StephenChou1017** [comment]
@nimesha95 
Hi，I add a SchedulerData.behaviors.getNonAgendaViewBodyCellBgColorFunc to change the background color of cells dynamically, and add a SchedulerData.behaviors.getScrollSpecialMomentFunc to scroll to a certain cell.

**Comment by nimesha95** [comment]
I'll check it out <3 thanks

**Comment by nimesha95** [comment]
Hi..
Tried accessing `getNonAgendaViewBodyCellBgColorFuncfunction`.. but it is undefined.
Currently on version 0.2.4
Any ideas?


![big-scheduler-snip](https://user-images.githubusercontent.com/20258167/48996943-0bb96580-f174-11e8-9fc2-162e2f8dca5f.PNG)

**Comment by nimesha95** [comment]
It was a typo.. Imported `getNonAgendaViewBodyCellBgColor `instead of `getNonAgendaViewBodyCellBgColorFunc`
