### ISSUE TITLE
How to achieve this type of Available slot?

### ISSUE THREAD

**Issue by Saikat-Sinha** [StephenChou1017/react-big-scheduler#59]
Thanks for this Awesome Component.

Currently i am trying to achieve this by creating Available as an event, is there any better way to achieve this?

**Comment by StephenChou1017** [comment]
@Saikat-Sinha 
Hi, can you explain it a little more?

**Comment by Saikat-Sinha** [comment]
Sorry my bad, It can be resolved using Event
