### ISSUE TITLE
Day view schedule is not showed correctly

### ISSUE THREAD

**Issue by henryroach** [StephenChou1017/react-big-scheduler#6]
Hello, I've tested day view but when the page is loaded for the first time, the day view is not loaded correctly.
You can check in Basic example: 
When I change the code at line 16 from
`let schedulerData = new SchedulerData('2017-12-18', ViewTypes.Week);`
to
`let schedulerData = new SchedulerData('2017-12-18', ViewTypes.Day);`
the view is not showed properly.

**Comment by StephenChou1017** [comment]
Hi, I've changed the view type to day view, but I didn't find where is wrong, can you tell me where is not shower properly in detail?:-)
Here is my screen shot:
![1](https://user-images.githubusercontent.com/12867932/40265396-308d60aa-5b6a-11e8-8225-b34566da9589.png)

**Comment by StephenChou1017** [comment]
@henryroach 
Hi, yes it's a bug and I've re-appeared it,  I should re-create the headers before re-creating the view data. I've fixed it and you may try it again, thank you:-)

**Comment by henryroach** [comment]
Great, it's working perfectly! Thank you! :-)
