### ISSUE TITLE
No events render on 0.2.5

### ISSUE THREAD

**Issue by apolzon** [StephenChou1017/react-big-scheduler#71]
After getting everything working on 0.2.2, I saw you published 0.2.5 today which fixes the css leaking issue from antd.

However, after upgrading to 0.2.5, no events are rendering, and no errors are thrown (the resources table renders fine). I've tried to dig through the changes, but I cannot for the life of me figure out what the issue is. My best guess is it has something to do with the DnD library version upgrade. I've attached a screenshot from the react devtools when running v0.2.5, and the state for the drop target component (rendered inside the scheduler-content-table) is empty and no context is defined. 

The Scheduler component has events and eventGroups props defined when inspecting via react devtools.

<img width="1435" alt="screen shot 2018-11-29 at 4 25 41 pm" src="https://user-images.githubusercontent.com/223493/49256421-960ffc80-f3f4-11e8-837e-a814a43c2db8.png">

I'm running react v16.4.1, in case that could have any effect on things as well.

**Comment by apolzon** [comment]
Closing. Turns out I had added react-dnd and react-dnd-html5-backend to my package in order to get the dragdropcontext hoc to work, and as they were locked to previous versions things were going all sorts of sideways. Updated them to match dependencies required by your package and all is good.

**Comment by KevinRodal** [comment]
@apolzon I'm having this same issue now. I've gone in and installed react-dnd and react-dnd-html5-backend with the appropriate versions. Was there anything else you needed to do to get it working? Here is the component I have wrapping the scheduler if you can see what I'm doing wrong.

`import React from 'react';

import Scheduler, {SchedulerData, ViewTypes } from 'react-big-scheduler'
import 'react-big-scheduler/lib/css/style.css'

import moment from 'moment';

import {DragDropContext} from 'react-dnd'
import HTML5Backend from 'react-dnd-html5-backend'

class DayScheduler extends React.Component {
    tempFunction() {
        console.log('temp');
    }

    render() {
        let now = moment();
        let dateHeader = now.format('MMMM Do YYYY');
        let schedulerData = new SchedulerData(now, ViewTypes.Day, true, false, {
            startResizable: false,
            endResizable: false,
            movable: false,
            creatable: false,
        });

        schedulerData.setResources(this.props.schedulerData.games);
        schedulerData.setEvents(this.props.schedulerData.events);

        return (
            <div>
                <h3>{dateHeader}</h3>
                <Scheduler schedulerData={schedulerData}
                    prevClick={this.tempFunction}
                    nextClick={this.tempFunction}
                    onSelectDate={this.tempFunction}
                    onViewChange={this.tempFunction}
                    eventItemClick={this.props.eventItemClick} />
            </div>
        );
    }
}

export default DragDropContext(HTML5Backend)(DayScheduler);`
