### ISSUE TITLE
[Bug] - dayStartFrom and dayStop don't work on custom period

### ISSUE THREAD

**Issue by ZomerVinicius** [StephenChou1017/react-big-scheduler#73]
This config set the day start to the hour I set,

And the day stop only to the last day of the period selected,

Not each day of the period,

Like the images below, that shows when I set **dayStartFrom** to **8** and **dayStop** to **18**:

![screenshot from 2018-11-28 16-50-21](https://user-images.githubusercontent.com/25743898/49174711-161f5f00-f32e-11e8-8597-e59391a478bb.png)
![screenshot from 2018-11-28 16-50-34](https://user-images.githubusercontent.com/25743898/49174719-1a4b7c80-f32e-11e8-9e44-907f5d0cd57b.png)
![screenshot from 2018-11-28 16-50-26](https://user-images.githubusercontent.com/25743898/49174724-1d466d00-f32e-11e8-82c6-ee8cdaa57bec.png)

**Comment by StephenChou1017** [comment]
@ZomerVinicius 
Hi, I've fixed this issue and checked in the code just now:-)

**Comment by ZomerVinicius** [comment]
Awesome, thank you !
