### ISSUE TITLE
Question - is there anyway of not render non-working hours?

### ISSUE THREAD

**Issue by canastro** [StephenChou1017/react-big-scheduler#74]
Looking at the API we have the option to hide the weekend by setting `displayWeekend` as false, is there any way or plans to add a feature to not display non-working hours?

**Comment by StephenChou1017** [comment]
@canastro 
Hi, if you just want to display working hours in day view, you may try to set schedulerData.config.dayStartFrom(defaults 0) and schedulerData.config.dayStopTo(defaults 23).

i.e. we start work at 9:00am and get off work at 6:00pm, we can set schedulerData.config.dayStartFrom to 9 and set schedulerData.config.dayStopTo to 18.

**Comment by avichovatiya67** [comment]
There is a feature to display non-working hours in different color, 
Is there any way to set non-working hours ?

**Comment by hbatalhaStch** [comment]
> 



> There is a feature to display non-working hours in different color, Is there any way to set non-working hours ?

https://github.com/StephenChou1017/react-big-scheduler/issues/124#issuecomment-1474128750
