### ISSUE TITLE
Events on Scheduler Day View not displaying

### ISSUE THREAD

**Issue by KevinRodal** [StephenChou1017/react-big-scheduler#80]
I've seen issue https://github.com/StephenChou1017/react-big-scheduler/issues/71 where the reporter said to install react-dnd and react-dnd-html5-backend. I've done this and it still doesn't seem to be working. A note is that the events and resources are displaying properly on the agenda view, and the resources render properly in the day view as well (just no events). Here is the component I have wrapping the scheduler if anyone can see what I'm doing wrong.

```
import React from 'react';

import Scheduler, {SchedulerData, ViewTypes } from 'react-big-scheduler'
import 'react-big-scheduler/lib/css/style.css'

import moment from 'moment';

import {DragDropContext} from 'react-dnd'
import HTML5Backend from 'react-dnd-html5-backend'

class DayScheduler extends React.Component {
    tempFunction() {
        console.log('temp');
    }

    render() {
        let now = moment();
        let dateHeader = now.format('MMMM Do YYYY');
        let schedulerData = new SchedulerData(now, ViewTypes.Day);

        schedulerData.setResources(this.props.schedulerData.games);
        schedulerData.setEvents(this.props.schedulerData.events);

        return (
            <div>
                <h3>{dateHeader}</h3>
                <Scheduler schedulerData={schedulerData}
                    prevClick={this.tempFunction}
                    nextClick={this.tempFunction}
                    onSelectDate={this.tempFunction}
                    onViewChange={this.tempFunction}
                    eventItemClick={this.props.eventItemClick} />
            </div>
        );
    }
}

export default DragDropContext(HTML5Backend)(DayScheduler);
```

One question that comes to mind is "Does the DragDropContext need to be on the outermost component?"

**Comment by StephenChou1017** [comment]
@KevinRodal 
Hi, you may create a brand new project using the instructions at [https://github.com/StephenChou1017/react-big-scheduler-demo](https://github.com/StephenChou1017/react-big-scheduler-demo), it should works.

**Comment by KevinRodal** [comment]
@StephenChou1017 thanks for pointing that out. I got react-big-scheduler-demo working locally. Then I  tried uninstalling all of my scheduler dependencies using npm then reinstalled using yarn and it worked *shrugs*

Thanks for the help!
